name: FirstWorkflow
on: workflow_dispatch
jobs:
  first-Job:
  runs-on: ubuntu-latest
  steps:
  - name: Print Message
    run: echo "darpan" 
    -name: Print Bye
    run: echo "Bye Darpan"cancel-timeout-minutes: 
